# Generated by Django 6.0.3 on 2026-04-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_category_created_by_tag_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('archived', 'В архиве'), ('deleted', 'Удален')], db_index=True, default='published', max_length=20, verbose_name='Статус'),
        ),
    ]
