# Generated by Django 6.0.3 on 2026-04-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comments/images/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='comment',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='comments/videos/%Y/%m/%d/', verbose_name='Видео'),
        ),
    ]
