# Generated by Django 6.0.3 on 2026-05-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_comment_image_comment_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Скрыт модерацией'),
        ),
    ]
