# Generated by Django 6.0.3 on 2026-05-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Скрыт модерацией'),
        ),
    ]
