# Generated by Django 6.0.3 on 2026-05-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_comment_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='moderation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина блокировки модерацией'),
        ),
    ]
