# Generated by Django 6.0.3 on 2026-06-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_moderation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='posts/images/%Y/%m/%d/', verbose_name='Изображение 2'),
        ),
        migrations.AddField(
            model_name='post',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='posts/images/%Y/%m/%d/', verbose_name='Изображение 3'),
        ),
        migrations.AddField(
            model_name='post',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='posts/images/%Y/%m/%d/', verbose_name='Изображение 4'),
        ),
        migrations.AddField(
            model_name='post',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='posts/images/%Y/%m/%d/', verbose_name='Изображение 5'),
        ),
        migrations.AddField(
            model_name='post',
            name='video2',
            field=models.FileField(blank=True, null=True, upload_to='posts/videos/%Y/%m/%d/', verbose_name='Видео 2'),
        ),
    ]
