# Generated by Django 6.0.3 on 2026-03-12 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='URL-идентификатор')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='Описание')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='communities/avatars/%Y/%m/%d/', verbose_name='Аватар')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='communities/covers/%Y/%m/%d/', verbose_name='Обложка')),
                ('privacy', models.CharField(choices=[('public', 'Публичное'), ('private', 'Закрытое'), ('hidden', 'Скрытое')], default='public', max_length=20, verbose_name='Приватность')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('closed', 'Закрыто'), ('deleted', 'Удалено')], default='active', max_length=20, verbose_name='Статус')),
                ('members_count', models.PositiveIntegerField(default=0, verbose_name='Участников')),
                ('posts_count', models.PositiveIntegerField(default=0, verbose_name='Постов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('admins', models.ManyToManyField(blank=True, related_name='admin_communities', to=settings.AUTH_USER_MODEL, verbose_name='Администраторы')),
                ('categories', models.ManyToManyField(blank=True, related_name='communities', to='posts.category', verbose_name='Категории')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_communities', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('tags', models.ManyToManyField(blank=True, related_name='communities', to='posts.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Сообщество',
                'verbose_name_plural': 'Сообщества',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Участник'), ('moderator', 'Модератор'), ('admin', 'Администратор')], default='member', max_length=20, verbose_name='Роль')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('banned', 'Заблокирован'), ('pending', 'Ожидает подтверждения')], default='active', max_length=20, verbose_name='Статус')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата вступления')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.community', verbose_name='Сообщество')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Участник сообщества',
                'verbose_name_plural': 'Участники сообществ',
            },
        ),
        migrations.AddField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(related_name='communities', through='communities.CommunityMembership', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Закреплен')),
                ('is_announcement', models.BooleanField(default=False, verbose_name='Объявление')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='communities.community', verbose_name='Сообщество')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='community_post', to='posts.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Пост сообщества',
                'verbose_name_plural': 'Посты сообществ',
                'ordering': ['-is_pinned', '-post__created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата приглашения')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата принятия')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='communities.community', verbose_name='Сообщество')),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invites', to=settings.AUTH_USER_MODEL, verbose_name='Приглашенный')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to=settings.AUTH_USER_MODEL, verbose_name='Пригласил')),
            ],
            options={
                'verbose_name': 'Приглашение',
                'verbose_name_plural': 'Приглашения',
                'unique_together': {('community', 'invitee')},
            },
        ),
        migrations.CreateModel(
            name='CommunityJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=500, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки')),
                ('approved', models.BooleanField(null=True, verbose_name='Одобрено')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='communities.community', verbose_name='Сообщество')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_requests', to=settings.AUTH_USER_MODEL, verbose_name='Обработал')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка на вступление',
                'verbose_name_plural': 'Заявки на вступление',
                'ordering': ['-created_at'],
                'unique_together': {('community', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='communitymembership',
            index=models.Index(fields=['community', 'role'], name='communities_communi_5808bc_idx'),
        ),
        migrations.AddIndex(
            model_name='communitymembership',
            index=models.Index(fields=['community', 'status'], name='communities_communi_8af3bc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='communitymembership',
            unique_together={('user', 'community')},
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['slug'], name='communities_slug_81f3ae_idx'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['-created_at', 'status'], name='communities_created_e9d483_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['community', '-is_pinned'], name='communities_communi_20bf6e_idx'),
        ),
    ]
