# Generated by Django 6.0.3 on 2026-03-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='privacy',
            field=models.CharField(choices=[('public', 'Публичное'), ('private', 'Закрытое (требуется одобрение)'), ('hidden', 'Скрытое (не отображается в списках)')], default='public', max_length=20, verbose_name='Приватность'),
        ),
    ]
