# Generated by Django 6.0.3 on 2026-05-17 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_alter_community_privacy'),
        ('posts', '0006_comment_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorized_communities', to='posts.category', verbose_name='Основная категория'),
        ),
        migrations.AddField(
            model_name='community',
            name='community_type',
            field=models.CharField(choices=[('public', 'Публичное'), ('private', 'Закрытое'), ('restricted', 'Ограниченное')], default='public', max_length=20, verbose_name='Тип сообщества'),
        ),
        migrations.AddField(
            model_name='community',
            name='discord',
            field=models.CharField(blank=True, max_length=100, verbose_name='Discord'),
        ),
        migrations.AddField(
            model_name='community',
            name='posts_need_approval',
            field=models.BooleanField(default=False, verbose_name='Посты требуют одобрения'),
        ),
        migrations.AddField(
            model_name='community',
            name='rules',
            field=models.TextField(blank=True, max_length=3000, verbose_name='Правила'),
        ),
        migrations.AddField(
            model_name='community',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='community',
            name='website',
            field=models.URLField(blank=True, verbose_name='Веб-сайт'),
        ),
    ]
