# Generated by Django 6.0.3 on 2026-06-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_community_category_community_community_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='restricted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата ограничения'),
        ),
        migrations.AddField(
            model_name='community',
            name='warning_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество предупреждений'),
        ),
        migrations.AlterField(
            model_name='community',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('restricted', 'Ограничено'), ('closed', 'Закрыто'), ('deleted', 'Удалено')], default='active', max_length=20, verbose_name='Статус'),
        ),
    ]
