# Generated by Django 6.0.3 on 2026-03-12 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_comments',
            field=models.BooleanField(default=True, verbose_name='Уведомления о комментариях'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_follows',
            field=models.BooleanField(default=True, verbose_name='Уведомления о подписчиках'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_likes',
            field=models.BooleanField(default=True, verbose_name='Уведомления о лайках'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_messages',
            field=models.BooleanField(default=True, verbose_name='Уведомления о сообщениях'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Email подтвержден'),
        ),
        migrations.AddField(
            model_name='user',
            name='github',
            field=models.CharField(blank=True, max_length=100, verbose_name='GitHub'),
        ),
        migrations.AddField(
            model_name='user',
            name='hide_email',
            field=models.BooleanField(default=True, verbose_name='Скрыть email'),
        ),
        migrations.AddField(
            model_name='user',
            name='message_privacy',
            field=models.CharField(choices=[('everyone', 'Все'), ('followers', 'Только подписчики'), ('none', 'Никто')], default='everyone', max_length=20, verbose_name='Кто может писать'),
        ),
        migrations.AddField(
            model_name='user',
            name='private_profile',
            field=models.BooleanField(default=False, verbose_name='Закрытый профиль'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='user',
            name='vk',
            field=models.CharField(blank=True, max_length=100, verbose_name='VK'),
        ),
    ]
