# Generated by Django 6.0.3 on 2026-05-12 21:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allow_comments',
            field=models.CharField(default='everyone', max_length=20, verbose_name='Кто может комментировать'),
        ),
        migrations.AddField(
            model_name='profile',
            name='allow_messages',
            field=models.CharField(default='everyone', max_length=20, verbose_name='Кто может писать'),
        ),
        migrations.AddField(
            model_name='profile',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='blocked_by', to=settings.AUTH_USER_MODEL, verbose_name='Заблокированные'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_comments',
            field=models.BooleanField(default=True, verbose_name='Комментарии'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_email',
            field=models.BooleanField(default=False, verbose_name='Email-уведомления'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_follows',
            field=models.BooleanField(default=True, verbose_name='Подписки'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_likes',
            field=models.BooleanField(default=True, verbose_name='Лайки'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_messages',
            field=models.BooleanField(default=True, verbose_name='Сообщения'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
    ]
