# Generated by Django 6.0.3 on 2026-05-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_allow_comments_profile_allow_messages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_platform_moderator',
            field=models.BooleanField(default=False, verbose_name='Модератор площадки'),
        ),
    ]
