# Generated by Django 6.0.3 on 2026-03-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Код подтверждения'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Код отправлен'),
        ),
    ]
