# Generated by Django 6.0.3 on 2026-05-17 07:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_platform_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='message_except',
            field=models.ManyToManyField(blank=True, related_name='message_excepted_by', to=settings.AUTH_USER_MODEL, verbose_name='Исключения для сообщений'),
        ),
        migrations.AddField(
            model_name='user',
            name='message_privacy_except',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Исключения (кто не может писать)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='message_privacy',
            field=models.CharField(choices=[('everyone', 'Все пользователи'), ('friends', 'Только друзья'), ('friends_except', 'Друзья, кроме...'), ('nobody', 'Только я')], default='everyone', max_length=20, verbose_name='Кто может писать'),
        ),
    ]
