# Generated by Django 6.0.3 on 2026-05-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_message_except_user_message_privacy_except_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='who_can_see_birthdate',
            field=models.CharField(default='friends', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='who_can_see_communities',
            field=models.CharField(default='everyone', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='who_can_see_friends',
            field=models.CharField(default='everyone', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='who_can_see_music',
            field=models.CharField(default='everyone', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='who_can_see_photos',
            field=models.CharField(default='everyone', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='who_can_see_profile',
            field=models.CharField(choices=[('everyone', 'Все'), ('friends', 'Друзья'), ('friends_friends', 'Друзья и друзья друзей'), ('nobody', 'Только я')], default='everyone', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='who_can_see_videos',
            field=models.CharField(default='everyone', max_length=20),
        ),
    ]
