# Generated by Django 6.0.3 on 2026-05-19 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_who_can_see_birthdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('accepted', 'Подтверждена'), ('rejected', 'Отклонена')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='friendship',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['user', 'status'], name='accounts_fr_user_id_a29a38_idx'),
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['friend', 'status'], name='accounts_fr_friend__3246ba_idx'),
        ),
    ]
