# Generated by Django 6.0.3 on 2026-05-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_friendship_status_friendship_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='who_can_see_birthdate',
            field=models.CharField(choices=[('everyone', 'Все'), ('friends', 'Только друзья'), ('nobody', 'Только я')], default='friends', max_length=20, verbose_name='Кто видит дату рождения'),
        ),
        migrations.AddField(
            model_name='profile',
            name='who_can_see_communities',
            field=models.CharField(choices=[('everyone', 'Все'), ('friends', 'Только друзья'), ('nobody', 'Только я')], default='everyone', max_length=20, verbose_name='Кто видит сообщества'),
        ),
        migrations.AddField(
            model_name='profile',
            name='who_can_see_friends',
            field=models.CharField(choices=[('everyone', 'Все'), ('friends', 'Только друзья'), ('nobody', 'Только я')], default='everyone', max_length=20, verbose_name='Кто видит друзей'),
        ),
        migrations.AddField(
            model_name='profile',
            name='who_can_see_music',
            field=models.CharField(default='everyone', max_length=20, verbose_name='Кто видит музыку'),
        ),
        migrations.AddField(
            model_name='profile',
            name='who_can_see_photos',
            field=models.CharField(choices=[('everyone', 'Все'), ('friends', 'Только друзья'), ('nobody', 'Только я')], default='everyone', max_length=20, verbose_name='Кто видит фото'),
        ),
        migrations.AddField(
            model_name='profile',
            name='who_can_see_profile',
            field=models.CharField(choices=[('everyone', 'Все'), ('friends', 'Только друзья'), ('nobody', 'Только я')], default='everyone', max_length=20, verbose_name='Кто видит профиль'),
        ),
        migrations.AddField(
            model_name='profile',
            name='who_can_see_videos',
            field=models.CharField(default='everyone', max_length=20, verbose_name='Кто видит видео'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Лайк'), ('comment', 'Комментарий'), ('follow', 'Подписка'), ('mention', 'Упоминание'), ('message', 'Сообщение'), ('community_invite', 'Приглашение в сообщество'), ('community_request', 'Заявка в сообщество'), ('report', 'Жалоба рассмотрена'), ('friend', 'Заявка в друзья'), ('friend_accept', 'Заявка принята')], max_length=20, verbose_name='Тип уведомления'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='allow_comments',
            field=models.CharField(choices=[('everyone', 'Все'), ('friends', 'Только друзья'), ('nobody', 'Только я')], default='everyone', max_length=20, verbose_name='Кто может комментировать'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='allow_messages',
            field=models.CharField(choices=[('everyone', 'Все'), ('friends', 'Только друзья'), ('friends_except', 'Друзья, кроме...'), ('nobody', 'Только я')], default='everyone', max_length=20, verbose_name='Кто может писать сообщения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Закрытый профиль'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='show_email',
            field=models.BooleanField(default=False, verbose_name='Показывать email в профиле'),
        ),
    ]
