# Generated by Django 6.0.3 on 2026-05-22 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_who_can_see_birthdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='who_can_see_stats',
            field=models.CharField(choices=[('everyone', 'Все'), ('friends', 'Только друзья'), ('nobody', 'Только я')], default='everyone', max_length=20, verbose_name='Кто видит статистику'),
        ),
    ]
