# Generated by Django 6.0.3 on 2026-06-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_who_can_see_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Лайк на посте'), ('like_comment', 'Лайк на комментарии'), ('comment', 'Комментарий'), ('reply', 'Ответ на комментарий'), ('follow', 'Подписка'), ('mention', 'Упоминание'), ('message', 'Сообщение'), ('community_invite', 'Приглашение в сообщество'), ('community_request', 'Заявка в сообщество'), ('community_post', 'Новый пост в сообществе'), ('report_resolved', 'Жалоба рассмотрена'), ('friend', 'Заявка в друзья'), ('friend_accept', 'Заявка принята')], max_length=20, verbose_name='Тип уведомления'),
        ),
    ]
