# Generated by Django 6.0.3 on 2026-06-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedphoto',
            name='original_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='savedphoto',
            name='source_post_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedvideo',
            name='original_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='savedvideo',
            name='source_post_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
