# Generated by Django 6.0.3 on 2026-06-07 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_storage', '0002_savedphoto_original_url_savedphoto_source_post_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='saved_media/%Y/%m/%d/')),
                ('media_type', models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео')], max_length=10)),
                ('original_url', models.URLField(max_length=500)),
                ('source_post_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_media', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
