# Generated by Django 6.0.3 on 2026-05-15 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnbanTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1000, verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], default='pending', max_length=20, verbose_name='Статус')),
                ('review_comment', models.TextField(blank=True, max_length=500, verbose_name='Комментарий модератора')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('ban', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unban_tickets', to='moderation.ban', verbose_name='Блокировка')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Рассмотрел')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unban_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Тикет на разбан',
                'verbose_name_plural': 'Тикеты на разбан',
                'ordering': ['-created_at'],
            },
        ),
    ]
