# Generated by Django 6.0.3 on 2026-05-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_unbanticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('lifted', 'Снято')], db_index=True, default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
