# Generated by Django 6.0.3 on 2026-05-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0003_alter_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ban',
            name='moderator_note',
            field=models.TextField(blank=True, max_length=500, verbose_name='Заметка для модераторов'),
        ),
    ]
