# Generated by Django 6.0.3 on 2026-06-08 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_community_category_community_community_type_and_more'),
        ('moderation', '0004_ban_moderator_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('rules_violation', 'Нарушение правил платформы'), ('spam', 'Спам / реклама'), ('nsfw', 'NSFW / 18+ контент'), ('hate_speech', 'Разжигание ненависти'), ('illegal', 'Противоправные действия'), ('fake', 'Фейковое / мошенническое сообщество'), ('other', 'Другое')], max_length=50, verbose_name='Причина')),
                ('description', models.TextField(help_text='Подробно опишите, что нарушено', verbose_name='Описание')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Жалоба одобрена'), ('rejected', 'Жалоба отклонена'), ('warning_issued', 'Выдано предупреждение'), ('restricted', 'Сообщество ограничено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('moderator_comment', models.TextField(blank=True, verbose_name='Комментарий модератора (виден создателю)')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='communities.community', verbose_name='Сообщество')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_community_reports', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_reports_made', to=settings.AUTH_USER_MODEL, verbose_name='Кто пожаловался')),
            ],
            options={
                'verbose_name': 'Жалоба на сообщество',
                'verbose_name_plural': 'Жалобы на сообщества',
                'ordering': ['-created_at'],
            },
        ),
    ]
