# Generated by Django 6.0.3 on 2026-06-08 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_community_restricted_at_community_warning_count_and_more'),
        ('moderation', '0005_communityreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_on_content', to='communities.community', verbose_name='Сообщество (если жалоба внутри)'),
        ),
        migrations.AddField(
            model_name='report',
            name='context',
            field=models.CharField(choices=[('platform', 'Платформа (вне сообществ)'), ('community', 'Внутри сообщества')], default='platform', max_length=20, verbose_name='Контекст жалобы'),
        ),
    ]
