# Generated by Django 6.0.3 on 2026-05-12 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=50, verbose_name='ID трека в Яндексе')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('artist', models.CharField(max_length=255, verbose_name='Исполнитель')),
                ('album', models.CharField(blank=True, max_length=255, verbose_name='Альбом')),
                ('cover_url', models.URLField(blank=True, max_length=500, verbose_name='Обложка')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='Длительность (сек)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_tracks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сохранённый трек',
                'verbose_name_plural': 'Сохранённые треки',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'track_id')},
            },
        ),
    ]
