# Generated by Django 6.0.3 on 2026-05-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0002_playlist_playlisttrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='cover',
            field=models.CharField(default='🎵', max_length=10),
        ),
    ]
