# Generated by Django 6.0.3 on 2026-05-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='messenger_files/%Y/%m/%d/', verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='message',
            name='file_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Тип файла'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, verbose_name='Содержание'),
        ),
    ]
