# Generated by Django 6.0.3 on 2026-06-08 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0006_message_reply_to'),
        ('posts', '0009_poll_polloption_pollvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='forwarded_poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_messages', to='posts.poll', verbose_name='Пересланный опрос'),
        ),
    ]
